# This workflow will install dependencies with pixi, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        environment: [py310, py311, py312]

    steps:
    - uses: actions/checkout@v4
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: latest
        environments: ${{ matrix.environment }}
    - name: Install dependencies
      run: |
        pixi install -e ${{ matrix.environment }}
    - name: Lint with flake8
      run: |
        pixi run -e ${{ matrix.environment }} lint
        pixi run -e ${{ matrix.environment }} lint-full
    - name: Test with pytest
      run: |
        pixi run -e ${{ matrix.environment }} test
    - name: Coveralls GitHub Action
      if: matrix.environment == 'py311' && matrix.os == 'ubuntu-latest'
      uses: coverallsapp/github-action@v2.3.0
      with:
        file: coverage.xml

            
